name: Streamlit Uygulamasini Uyanik Tut

on:
  schedule:
    # Her 4 saatte bir çalışır (Cron ifadesi)
    - cron: '0 */4 * * *'
  workflow_dispatch: # İsterseniz GitHub üzerinden elle de tetikleyebilirsiniz

jobs:
  ping:
    runs-on: ubuntu-latest
    steps:
      - name: Uygulamaya İstek Gönder
        run: |
          curl -I https://kibtek-data-knz7c69fis449g7rtdyxwk.streamlit.app
